In [1]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim.lr_scheduler import StepLR, MultiStepLR
import numpy as np
# import matplotlib.pyplot as plt
from math import *
import time

In [2]:
torch.cuda.set_device(2)
torch.set_default_tensor_type('torch.DoubleTensor')

In [3]:
# activation function
def activation(x):
    return x * torch.sigmoid(x)

In [4]:
# build FCNet 
class Net(torch.nn.Module):
    def __init__(self,input_width,layer_width):
        super(Net,self).__init__()
        self.layer_in = torch.nn.Linear(input_width, layer_width)
        self.layer1 = torch.nn.Linear(layer_width, layer_width)
        self.layer2 = torch.nn.Linear(layer_width, layer_width)
        self.layer_out = torch.nn.Linear(layer_width, 1)
    def forward(self,x):
        y = self.layer_in(x)
        y = activation(self.layer2(activation(self.layer1(y)))) # residual block 1
        output = self.layer_out(y)
        return output

In [5]:
dimension = 1

In [6]:
input_width,layer_width = dimension, 4

In [7]:
net = Net(input_width,layer_width).cuda() # network for u on gpu

In [8]:
# defination of exact solution
def u_ex(x):     
    temp = 1.0
    for i in range(dimension):
        temp = temp * torch.sin(pi*x[:, i])
    u_temp = 1.0 * temp
    return u_temp.reshape([x.size()[0], 1])

In [9]:
# defination of f(x)
def f(x):
    temp = 1.0
    for i in range(dimension):
        temp = temp * torch.sin(pi*x[:, i])
    u_temp = 1.0 * temp
    f_temp = dimension * pi**2 * u_temp 
    return f_temp.reshape([x.size()[0],1])

In [10]:
# generate points by random
def generate_sample(data_size):
    sample_temp = torch.rand(data_size, dimension)
    return sample_temp.cuda()

In [11]:
def model(x):
    x_temp = x.cuda()
    D_x_0 = torch.prod(x_temp, axis = 1).reshape([x.size()[0], 1]) 
    D_x_1 = torch.prod(1.0 - x_temp, axis = 1).reshape([x.size()[0], 1]) 
    model_u_temp = D_x_0 * D_x_1 * net(x)
    return model_u_temp.reshape([x.size()[0], 1])

In [12]:
# # Xavier normal initialization for weights:
# #             mean = 0 std = gain * sqrt(2 / fan_in + fan_out)
# # zero initialization for biases
# def initialize_weights(self):
#     for m in self.modules():
#         if isinstance(m,nn.Linear):
#             nn.init.xavier_normal_(m.weight.data)
#             if m.bias is not None:
#                 m.bias.data.zero_()

In [13]:
# # Uniform initialization for weights:
# #                  U(a, b)
# #             nn.init.uniform_(tensor, a = 0, b = 1)
# # zero initialization for biases
# def initialize_weights(self):
#     for m in self.modules():
#         if isinstance(m,nn.Linear):
#             nn.init.uniform_(m.weight.data)
#             if m.bias is not None:
#                 m.bias.data.zero_()

In [14]:
# Normal initialization for weights:
#               N(mean = 0, std = 1)
#             nn.init.normal_(tensor, a = 0, b = 1)
# zero initialization for biases
def initialize_weights(self):
    for m in self.modules():
        if isinstance(m,nn.Linear):
            nn.init.normal_(m.weight.data)
            if m.bias is not None:
                m.bias.data.zero_()

In [15]:
initialize_weights(net)

In [16]:
for name,param in net.named_parameters():
                print(name,param.size())
                print(param.detach().cpu())

layer_in.weight torch.Size([4, 1])
tensor([[ 0.6052],
        [ 0.2934],
        [ 1.5980],
        [-0.2812]])
layer_in.bias torch.Size([4])
tensor([0., 0., 0., 0.])
layer1.weight torch.Size([4, 4])
tensor([[-0.7762,  0.6250, -0.3043, -0.9242],
        [-0.6758,  1.2227, -0.4803,  0.6145],
        [ 0.7422, -1.5257, -0.8149, -0.7447],
        [ 1.3409,  0.8129, -0.0611,  0.2862]])
layer1.bias torch.Size([4])
tensor([0., 0., 0., 0.])
layer2.weight torch.Size([4, 4])
tensor([[ 1.3148, -1.9231,  0.8192,  0.6821],
        [-1.4513,  0.2206, -0.6673,  0.6838],
        [ 0.9120,  0.9919,  0.6188,  1.0709],
        [-2.1711, -0.3977, -0.5913,  0.2476]])
layer2.bias torch.Size([4])
tensor([0., 0., 0., 0.])
layer_out.weight torch.Size([1, 4])
tensor([[-0.7523, -1.2161, -1.2453,  0.5064]])
layer_out.bias torch.Size([1])
tensor([0.])


In [17]:
# loss function to DGM by auto differential
def loss_function(x):
#     x = generate_sample(data_size).cuda()
#     x.requires_grad = True
    u_hat = model(x)
    grad_u_hat = torch.autograd.grad(outputs = u_hat, inputs = x, grad_outputs = torch.ones(u_hat.shape).cuda(), create_graph = True)
    laplace_u = torch.zeros([len(grad_u_hat[0]), 1]).cuda()
    for index in range(dimension):
        p_temp = grad_u_hat[0][:, index].reshape([len(grad_u_hat[0]), 1])
        temp = torch.autograd.grad(outputs = p_temp, inputs = x, grad_outputs = torch.ones(p_temp.shape).cuda(), create_graph = True, allow_unused = True)[0]
        laplace_u = temp[:, index].reshape([len(grad_u_hat[0]), 1]) + laplace_u
        part_2 = torch.sum((-laplace_u - f(x))**2)  / len(x)
    return part_2

In [18]:
torch.save(net.state_dict(), 'net_params_DGM_FCNet_Normal.pkl')