In [1]:
import torch
import torch.nn as nn
import numpy as np
from math import *

In [2]:
# activation function
def activation(x):
    return x * torch.sigmoid(x)

In [3]:
# build ResNet with one blocks
class Net(torch.nn.Module):
    def __init__(self,input_width,layer_width):
        super(Net,self).__init__()
        self.layer_in = torch.nn.Linear(input_width, layer_width)
        self.layer1 = torch.nn.Linear(layer_width, layer_width)
        self.layer2 = torch.nn.Linear(layer_width, layer_width)
        self.layer_out = torch.nn.Linear(layer_width, 1)
    def forward(self,x):
        y = self.layer_in(x)
        y = y + activation(self.layer2(activation(self.layer1(y)))) # residual block 1
        output = self.layer_out(y)
        return output

In [4]:
dimension = 1

In [5]:
input_width,layer_width = dimension, 4

In [6]:
net = Net(input_width,layer_width)

In [7]:
# load model parameters
pretrained_dict = torch.load('net_params_DGM.pkl')

# get state_dict
net_state_dict = net.state_dict()

# remove keys that does not belong to net_state_dict
pretrained_dict_1 = {k: v for k, v in pretrained_dict.items() if k in net_state_dict}

# update dict
net_state_dict.update(pretrained_dict_1)

# set new dict back to net
net.load_state_dict(net_state_dict)

<All keys matched successfully>

In [8]:
param_DGM = torch.Tensor([0.])
for name,param in net.named_parameters(): 
    size = param.size()
    if len(size) == 2:
        print(param.detach().cpu().view(1, size[0]*size[1])[0])
        param_DGM = torch.cat((param_DGM, param.detach().cpu().view(1, size[0]*size[1])[0]), dim = 0)
    else:
        print(param.detach().cpu().view(1, size[0])[0])
        param_DGM = torch.cat((param_DGM, param.detach().cpu().view(1, size[0])[0]), dim = 0)

tensor([-0.2179, -0.7552,  0.4469,  1.1701])
tensor([-0.3287,  0.4343, -0.5646,  0.1575])
tensor([ 0.3002, -0.1030,  0.4684, -0.1617, -0.4345,  0.2642, -0.3147, -0.0879,
        -0.0642, -0.3641,  0.2832,  0.4977,  0.1660,  0.2771, -0.3677,  0.2634])
tensor([ 0.2304, -0.3868, -0.1135,  0.2150])
tensor([ 0.0746,  0.1486,  0.4689,  0.1757, -0.0850, -0.4909, -0.3872,  0.4143,
         0.0033, -0.2703, -0.2780, -0.1521, -0.2515,  0.4531,  0.0637, -0.1949])
tensor([-0.0615, -0.4916, -0.2522, -0.4868])
tensor([ 1.1556, -1.7318,  0.8062, -0.2845])
tensor([-0.2985])


In [9]:
# load model parameters
pretrained_dict = torch.load('net_params_DRM.pkl')

# get state_dict
net_state_dict = net.state_dict()

# remove keys that does not belong to net_state_dict
pretrained_dict_1 = {k: v for k, v in pretrained_dict.items() if k in net_state_dict}

# update dict
net_state_dict.update(pretrained_dict_1)

# set new dict back to net
net.load_state_dict(net_state_dict)

<All keys matched successfully>

In [10]:
param_DRM = torch.Tensor([0.])
for name,param in net.named_parameters(): 
    size = param.size()
    if len(size) == 2:
        print(param.detach().cpu().view(1, size[0]*size[1])[0])
        param_DRM = torch.cat((param_DRM, param.detach().cpu().view(1, size[0]*size[1])[0]), dim = 0)
    else:
        print(param.detach().cpu().view(1, size[0])[0])
        param_DRM = torch.cat((param_DRM, param.detach().cpu().view(1, size[0])[0]), dim = 0)

tensor([-1.5141,  0.6419,  1.7847, -0.0447])
tensor([-0.2507,  0.4893, -0.7086,  0.4046])
tensor([ 0.3002, -0.1030,  0.4684, -0.1617, -0.4345,  0.2642, -0.3147, -0.0879,
        -0.0642, -0.3641,  0.2832,  0.4977,  0.1660,  0.2771, -0.3677,  0.2634])
tensor([ 0.2304, -0.3868, -0.1135,  0.2150])
tensor([ 0.0746,  0.1486,  0.4689,  0.1757, -0.0850, -0.4909, -0.3872,  0.4143,
         0.0033, -0.2703, -0.2780, -0.1521, -0.2515,  0.4531,  0.0637, -0.1949])
tensor([-0.0615, -0.4916, -0.2522, -0.4868])
tensor([ 0.4888,  0.5074, -0.1846, -0.9395])
tensor([-0.1878])


In [11]:
error = torch.sum((param_DGM - param_DRM)**2)**0.5
print('Distance of two min is: ', error)

Distance of two min is:  tensor(3.7243)


In [12]:
error_max = torch.max((param_DGM - param_DRM)**2)
print('Distance of two min is: ', error_max**0.5)

Distance of two min is:  tensor(2.2392)
